### PR TITLE
Use six.string_types instead of basestring

### LINKED ISSUE #56: Autodiscover uses basestring, which does not exist in python 3
In `permission/utils/autodiscover.py`. Django suggests fixes here: https://docs.djangoproject.com/en/1.9/topics/python3/

### PR DESCRIPTION
**Pull request by lambdalisue**
Fix #56

### CODE REVIEW

**Comment by ElessarWebb** [comment]
Looks good. Is there a release plan on this?

**Comment by lambdalisue** [comment]
> Looks good. Is there a release plan on this?

Wait a minute. I need to support Django 1.2 and 1.3 as well

**Comment by lambdalisue** [comment]
Now the new version is released on PyPI

**Comment by ElessarWebb** [comment]
Wonderful. Thanks a lot!

**Comment by lambdalisue** [comment]
You are welcome. Feel free to create issues when you find:-]

**Pull request merged**
